version: '3.8'

services:
  postgres:
    image: postgres:14.2-alpine
    ports:
      - 8765:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=TestContext
